export const TOGGLE_SIGN_IN = 'toggleSignIn'
export const PLACE_ORDER_FROM_SOCKET = 'placeOrderFromSocket'
export const FINISH_GAME_FROM_SOCKET = 'placeOrderFromSocket'
export const PLACE_ORDER = 'placeOrder'
export const FINISH_GAME = 'finishGame'
